#!/bin/bash

# The script is not executing?
# Try "chmod +x fix_dependencies__a_bash_script"

echo "  This script MUST be executed from the project folder!"
#echo "  This script is self destructive."
read -p "  Are you ready to run it? (y/n) " yn

if [ y = 'y' ] || [ y = 'Y' ]; then
  
  src_str="github.com/ZverevM/netlink_legacy"
  tgt_str="github.com/ZverevM/netlink_legacy"
  
  find . -type f  \( -name "*.go" -o -name "*.md" -o -name "*.sh" \)  -print0 | \
    xargs -0 sed -i 's:'"github.com/vishvananda/netlink"':'"github.com/ZverevM/netlink_legacy"':g'
  #rm fix_dependencies__a_bash_script
  
fi
